#!/usr/bin/env python3
import os
import sys
import subprocess

exec = subprocess.call



PREFIX_DIR=os.path.join(os.getcwd(), "installation")
DATA_DIR=os.path.join(PREFIX_DIR, "data")

r = False
if os.path.exists("build") is False or (r:="-r" in sys.argv) is True:
    os.makedirs(os.path.join(DATA_DIR, "nxloader"), exist_ok=True)
    args = ["meson", "setup", "build", f"-Dprefix={PREFIX_DIR}", f"-Ddatadir={DATA_DIR}"]
    if r is True:
        args.insert(2, "--reconfigure")
    exec(args)

exec(["meson", "install"], cwd="build")
exec(["./installation/bin/nxloader"])

# #!/bin/bash
# if [ -d "build" ]; then
#     mkdir -p $(pwd)/installation/data/nxloader
#     meson build -Dprefix=$(pwd)/installation -Ddatadir=$(pwd)/installation/data
# fi

# cd build
# meson install
# cd ..
# ./installation/bin/nxloader